spring:
  application:
    name: pro_demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot3_demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 974946
    name: springboot3_demo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8 #?????
server:
  port: 9191
  servlet:
    context-path: /v1/api
